# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/eia_petroleum_prices.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/eia_petroleum_prices.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!protos/eia_petroleum_prices.proto\x12\x07scraper\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x01\n\x14PetroleumPriceRecord\x12\x12\n\nsource_url\x18\x01 \x01(\t\x12.\n\nfetch_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05units\x18\x03 \x01(\t\x12\x13\n\x0bperiod_date\x18\x04 \x01(\t\x12\x0f\n\x07product\x18\x05 \x01(\t\x12\x0e\n\x06region\x18\x06 \x01(\t\x12\x1c\n\x14price_usd_per_gallon\x18\x07 \x01(\x01\x12\r\n\x05grade\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.eia_petroleum_prices_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PETROLEUMPRICERECORD']._serialized_start=80
  _globals['_PETROLEUMPRICERECORD']._serialized_end=284
# @@protoc_insertion_point(module_scope)
